# Generated by Django 2.1.1 on 2018-09-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180912_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.IntegerField(choices=[(2, 'Komedia'), (3, 'Sci-Fi'), (0, 'Nieznany'), (1, 'Horror'), (4, 'Dramat')], default=0),
        ),
    ]
