# Generated by Django 2.1.1 on 2018-09-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180912_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=200)),
                ('movie2', models.ManyToManyField(to='main.Movie')),
            ],
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.IntegerField(choices=[(3, 'Sci-Fi'), (1, 'Horror'), (0, 'Nieznany'), (4, 'Dramat'), (2, 'Komedia')], default=0),
        ),
    ]
