# Generated by Django 2.1.1 on 2018-09-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180912_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.IntegerField(choices=[(4, 'Dramat'), (1, 'Horror'), (0, 'Nieznany'), (3, 'Sci-Fi'), (2, 'Komedia')], default=0),
        ),
    ]
