# Generated by Django 2.1.1 on 2018-09-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180918_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.IntegerField(choices=[(3, 'Sci-Fi'), (0, 'Nieznany'), (2, 'Komedia'), (1, 'Horror'), (4, 'Dramat')], default=0),
        ),
    ]
