# Generated by Django 2.1.1 on 2018-09-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180918_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.IntegerField(choices=[(3, 'Sci-Fi'), (1, 'Horror'), (0, 'Nieznany'), (2, 'Komedia'), (4, 'Dramat')], default=0),
        ),
    ]
