# Generated by Django 2.1.1 on 2018-09-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180918_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.IntegerField(choices=[(3, 'Sci-Fi'), (0, 'Nieznany'), (4, 'Dramat'), (2, 'Komedia'), (1, 'Horror')], default=0),
        ),
    ]
