# Generated by Django 2.1.1 on 2018-09-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180918_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.IntegerField(choices=[(2, 'Komedia'), (3, 'Sci-Fi'), (1, 'Horror'), (4, 'Dramat'), (0, 'Nieznany')], default=0),
        ),
    ]
