# Generated by Django 2.1.1 on 2018-09-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180918_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.IntegerField(choices=[(3, 'Sci-Fi'), (1, 'Horror'), (2, 'Komedia'), (0, 'Nieznany'), (4, 'Dramat')], default=0),
        ),
    ]
