# Generated by Django 2.1.1 on 2018-09-18 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180918_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.IntegerField(choices=[(2, 'Komedia'), (4, 'Dramat'), (0, 'Nieznany'), (1, 'Horror'), (3, 'Sci-Fi')], default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.ExtraInfo'),
        ),
    ]
