# Generated by Django 2.1.1 on 2018-09-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180918_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.IntegerField(choices=[(2, 'Komedia'), (0, 'Nieznany'), (3, 'Sci-Fi'), (1, 'Horror'), (4, 'Dramat')], default=0),
        ),
    ]
