# Generated by Django 2.1.1 on 2018-09-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180919_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.IntegerField(choices=[(3, 'Sci-Fi'), (1, 'Horror'), (4, 'Dramat'), (0, 'Nieznany'), (2, 'Komedia')], default=0),
        ),
    ]
